[ROCK-2116] Handle Discovery Token
Stratio/bdt pull request #623
Opened 2020-09-01 12:40 UTC by diegomartinez-stratio

Upgrate Discovery Token method with last versions.

Examples of use:
    

- Given I set sso token using host '!{DISCOVERY_HOST}/${DISCOVERY_ID:-discovery-qa}/auth' with user '${DCOS_TENANT1_OWNER_USER}' and password '${DCOS_TENANT1_OWNER_PASSWORD}' and tenant '${DCOS_TENANT1}' without host name verification with discovery cookie '${DCOS_TENANT1}-${DISCOVERY_ID:-discovery-qa}-auth-cookie'

- Given I obtain metabase id for user '${USER:-demo@stratio.com}' and password '${PASSWORD:-123456}' in endpoint 'https://!{DISCOVERY_HOST}/${DISCOVERY_ID:-discovery-qa}${DISCOVERY_SESSION:-/api/session}' and save in context cookies

2020-09-01 12:47 UTC, alopez-stratio approved these changes

2020-09-01 12:47 UTC, aalfonso-stratio requested changes

2020-09-01 12:47 UTC, aalfonso-stratio commented on src/main/java/com/stratio/qa/specs/DcosSpec.java
> +                tokenList = new String[]{discoveryCookie};
Estás sobreescribiendo tokenList, pero gov y discoveryCookie no son autoexcluyentes en el step.

2020-09-01 13:41 UTC, diegomartinez-stratio commented on src/main/java/com/stratio/qa/specs/DcosSpec.java
> +                tokenList = new String[]{discoveryCookie};
Para las peticiones de Discovery  las cookies "user", "dcos-acs-auth-cookie" no se generan por lo que al hacer la petición con una **url de discovery** si están incluidas las dejara a **null** por lo que no tiene mucho sentido dejarlas.

2020-09-01 14:42 UTC, aalfonso-stratio commented on src/main/java/com/stratio/qa/specs/DcosSpec.java
> +            if ((discoveryCookie != null) && (gov == null)) {
Sigue sin convencerme. Imagina que pongo este step:
* I set sso governance token using host 'myhost' with user 'myuser' and password 'mypassword' with discovery cookie 'mydiscoverycookie'
Se setea para governance y no para discovery a pesar de haber puesto ambas. Comportamiento confuso

2020-09-01 14:43 UTC, aalfonso-stratio commented on src/main/java/com/stratio/qa/specs/DcosSpec.java
> +            if ((discoveryCookie != null) && (gov == null)) {
Me sigue sin convencer, imagina que usas el step:
* I set sso governance token using host 'myhost' with user 'myuser' and password 'mypassword' with discovery cookie 'mydiscoverycookie'
Aquí sólo se setearía la info de governance a pesar de pedir las dos, es confuso

2020-09-02 05:37 UTC, aalfonso-stratio approved these changes

2020-09-02 06:42 UTC, merged