Make groups optional in JWT creation
Stratio/bdt pull request #703
Opened 2021-06-02 15:50 UTC by pbedia-stratio

2021-06-02 16:12 UTC, carlosgarcia-stratio requested changes

2021-06-02 16:12 UTC, carlosgarcia-stratio commented on src/main/java/com/stratio/qa/specs/MiscSpec.java
>          List<String> myList = new ArrayList<>();
Replace by: List<String> myList = groups == null ? new ArrayList<>() : new ArrayList<>(Arrays.asList(groups.split(",")));

2021-06-02 16:46 UTC, carlosgarcia-stratio approved these changes
LGTM

2021-06-03 06:14 UTC, amateos-stratio approved these changes
LGTM

2021-06-03 11:17 UTC, merged