[QATM-3704] Connect to external HDFS
Stratio/bdt pull request #709
Opened 2021-06-09 11:40 UTC by imorales-stratio

Scenario: Test HDFS
    Given I open connection to HDFS 'hdfs.epsilon.labs.stratio.com:8020' with principal 'sparktest' and keytab '/home/imorales/Descargas/sparktest.keytab' and realm 'REALM.DOM' and kdc 'public-agent03.golf.labs.stratio.com:88'
    Then I list content in HDFS directory '/tmp' and save it in environment variable 'hdfsCont'
    And I run 'echo !{hdfsCont}' locally
    And I close HDFS connection

2021-06-14 06:09 UTC, aalfonso-stratio commented on src/main/java/com/stratio/qa/specs/HDFSSecSpec.java
> +    @Given("^I open( privacy)? connection to HDFS '(.+?)' with principal '(.+?)' and keytab '(.+?)' and realm '(.+?)' and kdc '(.+?)'$")
No quedaría mejor: @Given("^I open( private)? connection to HDFS...

2021-06-14 06:09 UTC, aalfonso-stratio requested changes
mira el comentario

2021-06-14 07:57 UTC, imorales-stratio commented on src/main/java/com/stratio/qa/specs/HDFSSecSpec.java
> +    @Given("^I open( privacy)? connection to HDFS '(.+?)' with principal '(.+?)' and keytab '(.+?)' and realm '(.+?)' and kdc '(.+?)'$")
Correcto, actualizo

2021-06-15 06:41 UTC, imorales-stratio commented
@aalfonso-stratio ya lo deje corregido

2021-06-15 06:44 UTC, aalfonso-stratio approved these changes

2021-06-15 07:29 UTC, merged