[FRAM-7578] - Add delete statefulset
Stratio/bdt pull request #742
Opened 2021-12-03 08:01 UTC by mraposo-stratio

2021-12-03 08:02 UTC, imorales-stratio submitted a review, later dismissed

2021-12-03 08:02 UTC, pbedia-stratio submitted a review, later dismissed

2021-12-03 08:21 UTC, aalfonso-stratio requested changes

2021-12-03 08:21 UTC, aalfonso-stratio commented on src/main/java/com/stratio/qa/clients/k8s/KubernetesClient.java
> +     * @param service   Service to delete
el nombre del parámetro no es service

2021-12-03 11:48 UTC, alvarolopez-stratio approved these changes

2021-12-06 15:32 UTC, mraposo-stratio commented on src/main/java/com/stratio/qa/clients/k8s/KubernetesClient.java
> +     * @param service   Service to delete
Ya lo he cambiado

2021-12-09 08:29 UTC, aalfonso-stratio approved these changes

2021-12-09 08:33 UTC, merged