[FRAM-9115] Actualizacion a java 11
Stratio/bdt pull request #806
Opened 2022-07-08 09:38 UTC by ryuzvyak-stratio

Se ha comentado la clase AnotationsDoclet al estar deprecada en la version 11 de Java.
Se han probado los test con OpenSearch y han pasado correctamente.

2022-08-10 05:45 UTC, imorales-stratio commented on pom.xml
> +                <version>0.8.8</version>
Si quieres, si va a ser la misma versión que la definida arriba lo pondría como ${org.jacoco.core.version}

2022-09-06 06:41 UTC, imorales-stratio requested changes

2022-09-06 06:41 UTC, imorales-stratio commented on src/main/java/com/stratio/qa/doclet/AnnotationsDoclet.java
> +//    public static boolean start(DocletEnvironment root) throws IOException {
Hay que darle una vuelta antes de eliminarlo, si que es cierto que sale que está deprecado (https://docs.oracle.com/en/java/javase/11/docs/api/jdk.javadoc/com/sun/javadoc/Doclet.html), pero habría que ver la guía de migración para ver si es posible mantener esto

2022-09-06 06:41 UTC, imorales-stratio commented on pom.xml
> +<!--        <dependency>-->
Eliminar en vez de comentar si no es necesario

2022-09-06 06:41 UTC, imorales-stratio commented on pom.xml
> +<!--        <dependency>-->
Eliminar en vez de comentar si no es necesario

2022-09-06 06:41 UTC, imorales-stratio commented on Jenkinsfile
> +    BUILDTOOL_IMAGE = "qa.int.stratio.com:8443/stratio/qa-builder:0.3.0-PR14-SNAPSHOT"
```suggestion
    BUILDTOOL_IMAGE = "stratio/qa-builder:0.4.0-M1"
```

2022-09-06 06:41 UTC, imorales-stratio commented on pom.xml
> +<!--        <dependency>-->
Si no es algo que vaya a estar descomentado y fijo yo lo eliminaria

2022-09-06 06:41 UTC, imorales-stratio commented on pom.xml
> +<!--                    <execution>-->
Intentar mantener esta parte, ver la guia de migración

2022-09-15 05:07 UTC, imorales-stratio commented on pom.xml
> -                <executions>
Una duda, como has actualizado la clase AnnotationsDoclet, si añades esto, ¿sigue petando?

2022-09-15 07:11 UTC, imorales-stratio approved these changes

2022-09-15 07:29 UTC, alopez-stratio approved these changes

2022-09-15 10:14 UTC, merged