[FRAM-9220] Added patch functionality
Stratio/bdt pull request #830
Opened 2022-08-26 13:52 UTC by ryuzvyak-stratio

2022-08-29 06:05 UTC, imorales-stratio requested changes

2022-08-29 06:05 UTC, imorales-stratio commented on src/main/java/com/stratio/qa/specs/CommandExecutionSpec.java
> +    public void executePatch(String namespace, String clusterName, String instanceName, String operation, String path, String value, String sExitStatus) throws Exception {
Desde la BDT no deberiamos usar un comando con kubectl.

Habría que buscar la forma de hacerlo con la librería.

2022-08-29 06:32 UTC, imorales-stratio commented on src/main/java/com/stratio/qa/specs/CommandExecutionSpec.java
> +    public void executePatch(String namespace, String clusterName, String instanceName, String operation, String path, String value, String sExitStatus) throws Exception {
Adjunto un artículo donde parece que indica la forma: https://itnext.io/patch-kubernetes-resources-in-java-using-fabric8-kubernetes-client-25e0c68b9cb5

2022-09-05 08:10 UTC, imorales-stratio commented on src/main/java/com/stratio/qa/clients/k8s/KubernetesClient.java
> +            switch (path_descompuesto.size()) {
Por lo que veo, según el tamaño del path_descompuesto añadimos un .get adiccional al mapa. ¿quizá metiendo un for, que en cada iteracción vaya haciendo el get correspondiente, puede quedar mas limpio? (y asi si el tamaño es > 5 nos daría igual también :))

2022-09-05 14:39 UTC, alopez-stratio approved these changes

2022-09-06 07:14 UTC, merged